name: DEPLOY TO FIREBASE

on:
  push:
    branches:
      - development

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '12'
            check-latest: true
        - name: Installing project dependencies    
        - run: npm install
        - run: npm build
    #   uses: w9jds/firebase-action@master
    #     with:
    #       args: deploy --only hosting
    #     env:
    #       FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}