name: DEPLOY TO STAGING

on:
  push:
    branches:
      - development

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
            with:
                node-version: '12'
                check-latest: true
        - name: Installing project dependencies
        run: npm install
        - name: Building the project
        run: npm run build
    #   uses: w9jds/firebase-action@master
    #     with:
    #       args: deploy --only hosting
    #     env:
    #       FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}